### ISSUE TITLE
ivtc with avisynth is problematic

### ISSUE THREAD

**Issue by dtlnor** [iAvoe/deint-ivtc-web-tutorial#1]
https://github.com/iAvoe/deint-ivtc-web-tutorial/blob/d24e8002030c37abf3f9a7d9252c57e02391d4d6/HTML/index.html#L184-L200

1. Unlike the sample from VS, this AviSynth sample uses 2-pass TDecimate.
2. There is no TFM, no field match is done.
3. Unlike VFM, TFM performs deinterlacing on its own, using the `PP` parameter to specify how to handle it. When used together with QTGMC, the QTGMC clip should be assigned to `clip2` as an external deinterlacing clip, with a suitable `PP` value.

**Comment by iAvoe** [comment]
Decision: Get rid of QTGMC

**Comment by iAvoe** [comment]
Commit: https://github.com/iAvoe/deint-ivtc-web-tutorial/commit/84e7f702549b2c8d1f76bf90f67cfc73ef28749f
